application:
  catalogURI: http://dataset-catalogue:8080/catalogs/
  openDataEnhet: https://data.brreg.no/enhetsregisteret/api/enheter/
  openDataEnhetProxy: https://organization-catalogue.staging.fellesdatakatalog.digdir.no/organizations/

logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
spring:
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/datasetCatalog?authSource=admin&authMechanism=SCRAM-SHA-1
  security.oauth2.resourceserver.jwt.jwk-set-uri: ${JWK_KEY_SET_URI:https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/certs}

---
spring:
  profiles: develop
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/datasetCatalog?authSource=admin&authMechanism=SCRAM-SHA-1

---
spring:
  profiles: contract-test
server.port: 5555
