application:
  conceptCatalogueHost: http://fdk-nginx-search:8080/api
  organizationCatalogueHost: https://organization-catalogue.fellesdatakatalog.digdir.no/organizations


logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
spring:
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/datasetCatalog?authSource=admin&authMechanism=SCRAM-SHA-1
  security.oauth2.resourceserver.jwt.jwk-set-uri: ${JWK_KEY_SET_URI:https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/certs}

---
spring:
  profiles: develop
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/datasetCatalog?authSource=admin&authMechanism=SCRAM-SHA-1
application:
  conceptCatalogueHost: https://staging.fellesdatakatalog.digdir.no/api/
  organizationCatalogueHost: https://organization-catalogue.staging.fellesdatakatalog.digdir.no/organizations


---
spring:
  profiles: contract-test
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:5000/auth/realms/fdk/protocol/openid-connect/certs
server.port: 5555



