spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/${POSTGRESQL_DB:dataset_catalog}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security.oauth2.resourceserver.jwt.jwk-set-uri: ${OIDC_JWKS}
server.port: 8080
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        info: ping
        health: ready
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: dataset-catalog
application:
  fdkBaseHost: ${FDK_BASE_HOST}
  organizationCatalogHost: ${ORGANIZATION_CATALOG_HOST}
  catalogUriHost: ${FDK_REGISTRATION_BASE_URI}/catalogs
  datasetCatalogUriHost: ${DATASET_CATALOG_URI}/catalogs
  harvestAdminUri: ${ADMIN_API_BASE_URI}
  harvestDelay: 600000
  catalogHarvestRoute: dataset.publisher.HarvestTrigger
  newDataSourceRoute: dataset.publisher.NewDataSource
  exchangeName: harvests
security:
  fdkIssuer: ${OIDC_ISSUER:https://auth.staging.fellesdatakatalog.digdir.no/realms/fdk}
  corsOriginPatterns: "${CORS_ORIGIN_PATTERNS}"

---
spring:
  config.activate.on-profile: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/dataset_catalog
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
application:
  fdkBaseHost: https://staging.fellesdatakatalog.digdir.no
  organizationCatalogHost: https://organization-catalog.staging.fellesdatakatalog.digdir.no
  catalogUriHost: https://registrering.staging.fellesdatakatalog.digdir.no/catalogs
  harvestDelay: 10000
  catalogHarvestRoute: dataset.publisher.HarvestTrigger
  newDataSourceRoute: dataset.publisher.NewDataSource
  exchangeName: harvests
security.corsOriginPatterns: "*"

---
spring:
  config.activate.on-profile: contract-test
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:5050/realms/fdk/protocol/openid-connect/certs
server.port: 5555
application:
  fdkBaseHost: http://localhost:5050
  organizationCatalogHost: http://localhost:5050
  catalogUriHost: http://localhost:5050/catalogs
  harvestDelay: 10000
  catalogHarvestRoute: dataset.publisher.HarvestTrigger
  newDataSourceRoute: dataset.publisher.NewDataSource
  exchangeName: harvests
security.corsOriginPatterns: "*"

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/dataset_catalog
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SSO_HOST}/realms/fdk
          jwk-set-uri: ${SSO_HOST}/realms/fdk/protocol/openid-connect/certs
          audiences: dataset-catalog
          authorities-claim-name: authorities
          authority-prefix: ""
          authorities-claim-delimiter: ","
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  mvc:
    problemdetails:
      enabled: true
application:
  base-uri: ${BASE_URI:http://localhost}
  organization-catalog-base-uri: ${ORGANIZATION_CATALOG_BASE_URI:https://organization-catalog.staging.fellesdatakatalog.digdir.no}
  cors:
    originPatterns: "${CORS_ORIGIN_PATTERNS}"
