---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: dataset-catalog
  name: dataset-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: dataset-catalog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: dataset-catalog
    spec:
      containers:
        - name: dataset-catalog
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: dataset-catalog
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dataset-catalog
                  key: MONGODB_PASSWORD
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_HOST
            - name: MONGODB_REPLICASET
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_REPLICASET
            - name: MONGODB_AUTH
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MONGODB_AUTH
            - name: ORGANIZATION_CATALOG_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: ORGANIZATION_CATALOG_BASE_URI
            - name: FDK_BASE_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_BASE_URI
            - name: FDK_REGISTRATION_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_REGISTRATION_BASE_URI
            - name: OIDC_ISSUER
              valueFrom:
                secretKeyRef:
                  name: sso
                  key: SSO_OIDC_ISSUER
            - name: OIDC_JWKS
              valueFrom:
                secretKeyRef:
                  name: sso
                  key: SSO_OIDC_JWKS
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: RABBITMQ_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: RABBITMQ_PASSWORD
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: RABBITMQ_HOST
            - name: SEARCH_FULLTEXT_HOST
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: FDK_FULLTEXT_SEARCH_BASE_URI
            - name: DATASET_CATALOG_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: DATASET_CATALOG_BASE_URI
            - name: CORS_ORIGIN_PATTERNS
              valueFrom:
                secretKeyRef:
                  name: dataset-catalog
                  key: CORS_ORIGIN_PATTERNS
          image: dataset-catalog
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "750Mi"
              cpu: "20m"
            limits:
              memory: "750Mi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
status: {}
