apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: dataset-catalog
  name: dataset-catalog
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: dataset-catalog
status:
  loadBalancer: {}
