---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: dataset-catalog
  name: dataset-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: dataset-catalog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: dataset-catalog
    spec:
      containers:
        - name: dataset-catalog
          image: dataset-catalog
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "750Mi"
              cpu: "20m"
            limits:
              memory: "750Mi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
status: {}
