---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dataset-catalog-deployment.yaml
  - dataset-catalog-service.yaml
images:
  - name: dataset-catalog
    newName: ghcr.io/informasjonsforvaltning/dataset-catalog
    newTag: $(GIT_COMMIT_SHA)
